name: Deploy Theme

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run npm install
        run: npm install

      - name: Run rpm run zip
        run: npm run zip

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: theme
          path: dist/*.zip

      # notify discord
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" -d \
            '{"content": "## New ghost theme created\n\n[Download](${{ steps.artifact-upload-step.outputs.artifact-url }})"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
