name: Deploy Theme

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}

      # notify discord
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" -d \
            '{"content": "## New ghost theme uploaded\n\n**Version**: '"$(cat package.json | jq -r '.version')"'\n\n[View site](https://photo.james-hackett.ie)"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
